### ISSUE TITLE
compiling error

### ISSUE THREAD

**Issue by NanerLee** [blahgeek/Minions#1]
os: ubuntu 16.04.2
cargo: 0.16.0 (built 2017-03-13)
>    Compiling minions v0.1.0 (file:///home/****/Applications/Minions)
> error: struct field shorthands are unstable (see issue #37340)
>    --> src/frontend_gtk/app.rs:437:41
>     |
> 437 |                 Status::FilteringMoving{selected_idx, filter_text, filter_indices}
>     |                                         ^^^^^^^^^^^^
> 
> error: struct field shorthands are unstable (see issue #37340)
>    --> src/frontend_gtk/app.rs:437:55
>     |
> 437 |                 Status::FilteringMoving{selected_idx, filter_text, filter_indices}
>     |                                                       ^^^^^^^^^^^
> 
> error: struct field shorthands are unstable (see issue #37340)
>    --> src/frontend_gtk/app.rs:437:68
>     |
> 437 |                 Status::FilteringMoving{selected_idx, filter_text, filter_indices}
>     |                                                                    ^^^^^^^^^^^^^^
> 
> error: aborting due to 3 previous errors
> 
> error: Could not compile `minions`.
> 
> To learn more, run the command again with --verbose.

**Comment by blahgeek** [comment]
This project requires rust 1.18+
