### ISSUE TITLE
Please bundle libguile-2.0.so.22

### ISSUE THREAD

**Issue by probonopd** [blahgeek/Minions#2]
Running `Minions-0.1.0-x86_64.AppImage` on openSUSE LEAP 42.2 I get:

```
xbindkeys: error while loading shared libraries: libguile-2.0.so.22: cannot open shared object file: No such file or directory
```

**Comment by blahgeek** [comment]
Thanks for your feedback! I'll check that

(and hey, it's so nice to meet the author of AppImage! I just started trying it today and I think it is awesome)

**Comment by blahgeek** [comment]
hi @probonopd 
I bundled the libguile.xxx.so file, but it still fail to run. It seems that libguile requires some resource files under /usr/share/guile. Is there any generic way to bundle these files? Or do I have to do it manually?

**Comment by probonopd** [comment]
You would have to do this manually. Also please ask the guile developers how to make guile relocatable (so that it runs from whatever location other than `/usr`). AppImages are mounted to a different mount point each time.

**Comment by blahgeek** [comment]
Ok, thanks!

But anyway, I've already modified my code and removed the use of libguile, so this issue can be closed now.
